import React from 'react';
import { Slider } from "@/components/ui/slider";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { RotateCcw, ChevronDown } from 'lucide-react';
import { useLanguage } from '@/components/i18n/LanguageContext';

const countries = ["Germany", "Netherlands", "Czech Republic", "Poland", "Hungary", "Austria", "France", "Italy", "Spain", "Portugal", "Belgium", "Sweden", "Finland", "Norway", "Denmark", "Switzerland", "United Kingdom", "Ireland", "USA", "Canada", "Australia", "China", "South Korea", "Japan", "Singapore", "Malaysia", "UAE"];
const languages = ["English", "German", "French", "Spanish", "Italian", "Dutch", "Russian", "Mixed"];
const regions = ["Europe", "North America", "Asia", "Middle East", "Oceania", "South America"];
const degrees = ["Bachelor", "Master", "PhD"];

export default function FilterPanel({ filters, setFilters, onReset, universities = [] }) {
    const { t } = useLanguage();
    const [showAdvanced, setShowAdvanced] = React.useState(false);
    const availableCountries = React.useMemo(() => {
        if (!universities || universities.length === 0) return countries;
        const countrySet = new Set(universities.map(u => u.country).filter(Boolean));
        return countries.filter(c => countrySet.has(c));
    }, [universities]);
    const updateFilter = (key, value) => setFilters(prev => ({ ...prev, [key]: value }));
    const toggleArrayFilter = (key, value) => setFilters(prev => { const current = prev[key] || []; const updated = current.includes(value) ? current.filter(v => v !== value) : [...current, value]; return { ...prev, [key]: updated }; });
    const activeFilterCount = Object.values(filters).filter(v => v !== null && v !== undefined && v !== "" && (Array.isArray(v) ? v.length > 0 : true)).length;
    return (
        <div className="bg-white rounded-2xl border border-slate-100 p-6 space-y-6 shadow-sm">
            <div className="flex items-center justify-between"><h3 className="font-semibold text-slate-800">{t('search.filters')}</h3>{activeFilterCount > 0 && <Button variant="ghost" size="sm" onClick={onReset} className="text-slate-500 hover:text-slate-700"><RotateCcw className="w-4 h-4 mr-1" />{t('filters.reset')}</Button>}</div>
            <div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.gpa')}: <span className="text-indigo-600 font-semibold">{filters.gpa?.toFixed(1) || "Any"}</span></Label><Slider value={[filters.gpa || 2.0]} onValueChange={([val]) => updateFilter('gpa', val)} min={1.0} max={4.0} step={0.1} className="py-2" /><div className="flex justify-between text-xs text-slate-400"><span>1.0</span><span>4.0</span></div></div>
            <div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.ielts')}: <span className="text-indigo-600 font-semibold">{filters.ielts === 0 ? t('filters.noCertificate') : filters.ielts?.toFixed(1)}</span></Label><Select value={String(filters.ielts || 0)} onValueChange={(val) => updateFilter('ielts', Number(val))}><SelectTrigger className="bg-slate-50 border-slate-200"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">{t('filters.noCertificate')}</SelectItem><SelectItem value="5.5">IELTS 5.5</SelectItem><SelectItem value="6.0">IELTS 6.0</SelectItem><SelectItem value="6.5">IELTS 6.5</SelectItem><SelectItem value="7.0">IELTS 7.0+</SelectItem></SelectContent></Select></div>
            <div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.topik')}: <span className="text-indigo-600 font-semibold">{filters.topikLevel === "Not taken" ? t('filters.notTaken') : filters.topikLevel}</span></Label><Select value={filters.topikLevel || "Not taken"} onValueChange={(val) => updateFilter('topikLevel', val)}><SelectTrigger className="bg-slate-50 border-slate-200"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Not taken">{t('filters.notTaken')}</SelectItem><SelectItem value="TOPIK 1">TOPIK 1</SelectItem><SelectItem value="TOPIK 2">TOPIK 2</SelectItem><SelectItem value="TOPIK 3">TOPIK 3</SelectItem><SelectItem value="TOPIK 4">TOPIK 4</SelectItem><SelectItem value="TOPIK 5">TOPIK 5</SelectItem><SelectItem value="TOPIK 6">TOPIK 6</SelectItem></SelectContent></Select></div>
            <div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.budget')}: <span className="text-indigo-600 font-semibold">€{filters.budget?.toLocaleString() || "Any"}/{t('common.year')}</span></Label><Slider value={[filters.budget || 20000]} onValueChange={([val]) => updateFilter('budget', val)} min={0} max={50000} step={500} className="py-2" /><div className="flex justify-between text-xs text-slate-400"><span>€0</span><span>€50,000+</span></div></div>
            <div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.country')}</Label><Select value={filters.country || ""} onValueChange={(val) => updateFilter('country', val)}><SelectTrigger className="bg-slate-50 border-slate-200"><SelectValue placeholder={t('filters.allCountries')} /></SelectTrigger><SelectContent><SelectItem value="all">{t('filters.allCountries')}</SelectItem>{availableCountries.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>
            <Button variant="outline" onClick={() => setShowAdvanced(!showAdvanced)} className="w-full">{showAdvanced ? 'Hide' : 'More'} {t('search.filters')}<ChevronDown className={`w-4 h-4 ml-2 transition-transform ${showAdvanced ? 'rotate-180' : ''}`} /></Button>
            {showAdvanced && <div className="space-y-6 pt-4 border-t"><div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.region')}</Label><Select value={filters.region || ""} onValueChange={(val) => updateFilter('region', val)}><SelectTrigger className="bg-slate-50 border-slate-200"><SelectValue placeholder={t('filters.allRegions')} /></SelectTrigger><SelectContent><SelectItem value="all">{t('filters.allRegions')}</SelectItem>{regions.map(r => <SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></div><div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.language')}</Label><div className="flex flex-wrap gap-2">{languages.map(lang => <Badge key={lang} variant={filters.languages?.includes(lang) ? "default" : "outline"} className={`cursor-pointer transition-all ${filters.languages?.includes(lang) ? "bg-indigo-600 hover:bg-indigo-700" : "hover:bg-slate-100"}`} onClick={() => toggleArrayFilter('languages', lang)}>{lang}</Badge>)}</div></div><div className="space-y-3"><Label className="text-sm font-medium text-slate-700">{t('filters.degree')}</Label><div className="flex flex-wrap gap-2">{degrees.map(deg => <Badge key={deg} variant={filters.degree === deg ? "default" : "outline"} className={`cursor-pointer transition-all ${filters.degree === deg ? "bg-indigo-600 hover:bg-indigo-700" : "hover:bg-slate-100"}`} onClick={() => updateFilter('degree', filters.degree === deg ? '' : deg)}>{deg}</Badge>)}</div></div><div className="space-y-3"><label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={filters.scholarshipsOnly || false} onChange={(e) => updateFilter('scholarshipsOnly', e.target.checked)} className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500" /><span className="text-sm text-slate-700">{t('filters.scholarships')}</span></label></div></div>}
        </div>
    );
}
